### ISSUE TITLE
Text fields not contained by modal & modal goes off screen

### ISSUE THREAD

**Issue by 06000208** [ryanjamurphy/vantage-obsidian#8]
I have similar issues to #3 and #4.

On one of my monitors with a resolution of 1280x1024, the text inputs for searching note content go outside of vantage's modal in the horizontal direction and cannot be reached:

![image](https://user-images.githubusercontent.com/52764066/123079804-e2bbe880-d3e1-11eb-81ab-ed8109d70773.png)

On another monitor with a resolution of 1024x768, the modal goes off the screen vertically and the X to close it cannot be reached:

![image](https://user-images.githubusercontent.com/52764066/123080017-1b5bc200-d3e2-11eb-9019-920c7c313cbc.png)

Using vantage 1.4.0 and obsidian 0.12.5 on windows 10 with no css snippets or theming.

**Comment by 06000208** [comment]
Some fixes via css snippets
```css
.vantage-modal .setting-item-control {
  flex-wrap: wrap;
}
/* these aren't necessary but make it nicer */
.vantage-modal .setting-item-control {
  justify-content: flex-start;
  gap: 0.5em;
}
.vantage-modal .setting-item-info:empty {
  display: none;
}
```
```css
.vantage-modal {
  height: 80vh;
}
```
